GET http://localhost:8000/users

GET http://localhost:8000/users/:{Your Test UserId}

POST http://localhost:8000/users
Content-Type: application/json

{
    "id": "Test UserId1",
    "name": "Test UserName1",
    "password": "Test UserPassword1",
    "tel": "Test UserTel1",
    "address": "Test UserAddress1",
    "detailAddress": "Test UserDetailAddress1"
}

PUT http://localhost:8000/users/:{Your Test UserId}
Content-Type: application/json

{
    "name": "Test UserName2",
    "password": "Test UserPassword2",
    "tel": "Test UserTel2",
    "address": "Test UserAddress2",
    "detailAddress": "Test UserDetailAddress2"
}

DELETE http://localhost:8000/users/:{Your Test UserId}