spring:
    devtools:
        livereload:
            enabled: false
    # Spring Boot default profile active : local
    profiles:
        active: local
    # Spring Boot output log colorize
    output:
        ansi:
            enabled: always
    sql:
        init:
            mode: always
            schema-locations: classpath:schema-mysql.sql
            data-locations: classpath:data-mysql.sql

springdoc:
    packages-to-scan: com.boardapp.boardapi
    swagger-ui:
        path: /swagger-ui.html              # Swagger UI page route path
        tags-sorter: alpha                  # Sort with alphanum
        operations-sorter: alpha            # Sort with alphanum
    api-docs:
        path: /api-docs/json                # API document file route path
        groups:
            enabled: true                     #
    cache:
        disabled: true                      # Cache disable