server:
    port: 8000

logging:
    level:
        # root: DEBUG
        org:
            springframework:
                jdbc:
                    core:
                        JdbcTemplate: DEBUG
                        StatementCreatorUtils: TRACE

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/boards?allowPublicKeyRetrieval=true&connectionTimeZone=UTC&characterEncoding=EUC-KR
        username: root
        password: 123456
    cache:
        type: redis
    data:
        redis:
            host: localhost
            port: 6379