### Tomcat server listening port
server:
    port: 8000

### Spring boot logging level
# logging:
#     level:
#         org:
#             springframework: DEBUG

# HikariPool Connection
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        # driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mysql://localhost:3307?allowPublicKeyRetrieval=true
        # url: jdbc:mariadb://localhost:3306
        username: root
        password: 123456