spring:
    devtools:
        livereload:
            enabled: false
    profiles:
        active: local
    output:
        ansi:
            enabled: always
    sql:
        init:
            mode: always
            schema-locations: classpath:database/schema-mysql.sql
            data-locations: classpath:database/data-mysql.sql

sub:
    test: ok