spring:
    devtools:
        livereload:
            enabled: false
    # Spring Boot default profile active : local
    profiles:
        active: local
    jpa:
        open-in-view: false
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate: 
                format_sql: true
    # Spring Boot output log colorize
    output:
        ansi:
            enabled: always

# Spring Doc OpenAPI Configuration
springdoc:
    packages-to-scan: com.boardapp.boardapi
    # Config Contents Media Type
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    swagger-ui:
        path: /swagger-ui.html               # Swagger UI Route Path : http://localhost:<Port Num.>/swagger-ui.html
        disable-swagger-default-url: true
        display-request-duration: true
        tags-sorter: alpha                  # alpha: Tag sort by alphanumeric, method: Sort by HTTP Method 
        operations-sorter: method            # alpha: Tag sort by alphanumeric, method: Sort by HTTP Method
    api-docs:
        path: /api-docs/json
        groups:
            enabled: true
    cache:
        disabled: true
###